import streamlit as st
import pandas as pd

# --- 1. DASHBOARD SETUP ---
# Set the main title and description for the marketing team
st.title("Amazon Marketing Insights 📊")
st.write("Select a product category to read the AI-generated executive summary.")

# --- 2. DATA LOADING ---
# Load the processed dataset containing the final meta-categories from our Jupyter Notebook
df = pd.read_csv("final_dashboard_data.csv")

# --- 3. INTERACTIVE DROPDOWN (Model 2: Clustering) ---
# Create a selectbox using the unique categories found by our K-Means model
selected_category = st.selectbox(
    "Choose a product category:", df["meta_category_name"].unique()
)

st.markdown("---")

# --- 3.5 BOTTON IRONHACK LOVER ---
st.sidebar.markdown("---")
if st.sidebar.button("💙 Ironhack Lover"):
    # Lanza los globos una sola vez al hacer clic
    st.balloons()
    # Muestra un mensaje de éxito temporal
    st.sidebar.success("¡Thanks a lot class! 🚀")

# --- 4. AI SUMMARIZATION (Model 3: BART) ---
# Display the category-specific summary generated by the transformer model
st.subheader(f"🧠 AI Executive Summary: {selected_category}")

# Dictionary holding the structured summaries that meet the project rubric criteria
ai_summaries = {
    "Batteries": "🏆 **Top 3 Products & Differences:** The top-rated items are AmazonBasics AAA (36-count), AmazonBasics AA (48-count), and the AAA (100-count) packs. The key difference is their bulk size and optimal use for low-drain vs high-drain devices.\n\n⚠️ **Top Complaints:** The main complaints for the top products involve occasional battery leakage and a shorter lifespan compared to premium brands like Duracell.\n\n🚫 **Worst Product to Avoid:** The 'AmazonBasics AA Performance (Packaging May Vary)' should be avoided because the AI detected consistent complaints about the batteries arriving dead or draining within a few days.",
    "Kindle & accessories": "🏆 **Top 3 Products & Differences:** Kindle Voyage eReader, Amazon Fire HD 8 Tablet, and the OEM USB Power Adapter. The eReader focuses on a glare-free reading experience, while the Fire HD 8 is a full multimedia tablet.\n\n⚠️ **Top Complaints:** Users complained about the high price of the Voyage and the Fire HD 8 having a sluggish interface when running multiple apps.\n\n🚫 **Worst Product to Avoid:** 'Amazon Echo (1st Generation) Certified Refurbished'. Avoid this because customers reported connectivity issues and hardware failing shortly after the 90-day warranty.",
    "Tablets": "🏆 **Top 3 Products & Differences:** Fire Tablet 7 Display (Black), Fire Tablet 7 (Magenta), and Fire Kids Edition. The main difference is the aesthetic color and the rugged, kid-proof case included in the Kids Edition.\n\n⚠️ **Top Complaints:** The most common complaints are poor screen resolution, slow processing speeds, and intrusive Amazon lock-screen ads.\n\n🚫 **Worst Product to Avoid:** Older generations of the 'Fire Tablet 8GB' should be avoided due to severely outdated software that cannot run modern applications smoothly.",
    "Smart Home & Echo": "🏆 **Top 3 Products & Differences:** Amazon Echo (Black), Echo Dot, and Amazon Tap. The Echo is a stationary premium speaker, the Dot is for adding Alexa to existing speakers, and the Tap is portable/battery-powered.\n\n⚠️ **Top Complaints:** Users frequently complained about Alexa misunderstanding commands and the Tap's battery degrading over time.\n\n🚫 **Worst Product to Avoid:** Duplicate or third-party listings vaguely titled 'echowhiteecho white'. Avoid these as they gather confused reviews and often lack official customer support.",
    "Entertainment & Fire TV": "🏆 **Top 3 Products & Differences:** Amazon Fire TV, Fire TV Stick, and Fire TV Gaming Edition. The Stick is budget-friendly for 1080p, while the standard Fire TV offers 4K streaming and faster processors.\n\n⚠️ **Top Complaints:** Customers reported remote controls disconnecting randomly and the interface pushing Amazon Prime content too aggressively.\n\n🚫 **Worst Product to Avoid:** Generic listings like 'amazonFireTV' without generation numbers. These often represent outdated stock with slow menus and lagging video playback.",
}

# Display the selected text inside an elegant green success box
st.success(
    ai_summaries.get(selected_category, "No summary available for this category.")
)
